//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace VikingFinancial.Data.Transaction
{

    public partial class Credit : Transaction
    {
        CreditCategory fCategory;
        [Association(@"DepositReferencesDepositCategory")]
        public CreditCategory Category
        {
            get { return fCategory; }
            set { SetPropertyValue<CreditCategory>(nameof(Category), ref fCategory, value); }
        }
    }

}
