//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace VikingFinancial.Data.Transaction
{

    public partial class DebitCategory : XPObject
    {
        string fTitle;
        public string Title
        {
            get { return fTitle; }
            set { SetPropertyValue<string>(nameof(Title), ref fTitle, value); }
        }
        bool fIsLocked;
        [ColumnDefaultValue(false)]
        public bool IsLocked
        {
            get { return fIsLocked; }
            set { SetPropertyValue<bool>(nameof(IsLocked), ref fIsLocked, value); }
        }
        [Association(@"WithdrawalReferencesWithdrawalCategory")]
        public XPCollection<Debit> Withdrawals { get { return GetCollection<Debit>(nameof(Withdrawals)); } }
        [Association(@"BudgetItemReferencesDebitCategory")]
        public XPCollection<BudgetItem> BudgetItems { get { return GetCollection<BudgetItem>(nameof(BudgetItems)); } }
    }

}
