//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace VikingFinancial.Data.Transaction
{

    public partial class Transaction : XPObject
    {
        decimal fAmount;
        public decimal Amount
        {
            get { return fAmount; }
            set { SetPropertyValue<decimal>(nameof(Amount), ref fAmount, value); }
        }
        string fNote;
        [Size(SizeAttribute.Unlimited)]
        public string Note
        {
            get { return fNote; }
            set { SetPropertyValue<string>(nameof(Note), ref fNote, value); }
        }
        DateTime fDateCreated;
        public DateTime DateCreated
        {
            get { return fDateCreated; }
            set { SetPropertyValue<DateTime>(nameof(DateCreated), ref fDateCreated, value); }
        }
        DateTime fDateTransaction;
        public DateTime DateTransaction
        {
            get { return fDateTransaction; }
            set { SetPropertyValue<DateTime>(nameof(DateTransaction), ref fDateTransaction, value); }
        }
        UserProfile fAddedByUser;
        [Association(@"TransactionReferencesUserProfile")]
        public UserProfile AddedByUser
        {
            get { return fAddedByUser; }
            set { SetPropertyValue<UserProfile>(nameof(AddedByUser), ref fAddedByUser, value); }
        }
        TransactionType fType;
        [Association(@"TransactionReferencesTransactionType")]
        public TransactionType Type
        {
            get { return fType; }
            set { SetPropertyValue<TransactionType>(nameof(Type), ref fType, value); }
        }
        TransactionCategory fCategory;
        [Association(@"TransactionReferencesTransactionCategory")]
        public TransactionCategory Category
        {
            get { return fCategory; }
            set { SetPropertyValue<TransactionCategory>(nameof(Category), ref fCategory, value); }
        }
    }

}
