//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace VikingFinancial.Data.Transaction
{

    public partial class UserProfile : XPObject
    {
        string fUsername;
        [Size(25)]
        public string Username
        {
            get { return fUsername; }
            set { SetPropertyValue<string>(nameof(Username), ref fUsername, value); }
        }
        string fPassword;
        [Size(SizeAttribute.Unlimited)]
        public string Password
        {
            get { return fPassword; }
            set { SetPropertyValue<string>(nameof(Password), ref fPassword, value); }
        }
        byte[] fSalt;
        [MemberDesignTimeVisibility(true)]
        public byte[] Salt
        {
            get { return fSalt; }
            set { SetPropertyValue<byte[]>(nameof(Salt), ref fSalt, value); }
        }
        bool fIsAdmin;
        [ColumnDefaultValue(false)]
        public bool IsAdmin
        {
            get { return fIsAdmin; }
            set { SetPropertyValue<bool>(nameof(IsAdmin), ref fIsAdmin, value); }
        }
        [Association(@"TransactionReferencesUserProfile")]
        public XPCollection<Transaction> Transactions { get { return GetCollection<Transaction>(nameof(Transactions)); } }
    }

}
